### ISSUE TITLE
'Failed to resolve: com.afollestad:material-dialogs:0.6.3.3' upon initial build

### ISSUE THREAD

**Issue by auxdesigner** [juankysoriano/Zen#1]
Screenshot: https://dl.dropboxusercontent.com/u/27322742/screenshot.png

According to https://github.com/afollestad/material-dialogs/, I updated it to "com.afollestad:material-dialogs:0.7.5.5" and it worked.

**Comment by juankysoriano** [comment]
@auxdesigner , thanks for this, I didn't notice this before,  probably because I already have all my dependencies as local so | didn't have to resolve that dependency which obviously is not in the repositories anymore. Moreover my jenkins machine is down so I couldn't notice it there neither.

Also, I will open a TODO to make sure that at some point I update all dependencies libraries to the latest available. Feel free to open other issues if you find more.

**Comment by juankysoriano** [comment]
Fixed.
